### ISSUE TITLE
Topsy + non-topsy chording is still weird

### ISSUE THREAD

**Issue by algernon** [keyboardio/Kaleidoscope-TopsyTurvy#5]
When holding a Topsy and a non-Topsy key, it correctly repeats the non-Topsy key, but with `Shift` applied. When we run into a case like this, we should cancel out the Topsy effects, as if it was released.

**Comment by Llamalland** [comment]
Some interesting behaviour I've noticed (more relevant to the closed issue #6 ) in case it's relevant: I have a topsy semicolon so I can use the colon unshifted and keys that are lshift-9 and lshift-0 (because I wanted the parentheses but not the numbers and was aware of this issue), and when I hold the topsy key and tap the shift keys, lshift-9 works as expected but lshift-0 gives repeating symbols, with the colon appearing once when you hit that key but the close parentheses repeating whenever both are held. Both repeat just fine on their own.
